### ISSUE TITLE
Support Alfred 4 request

### ISSUE THREAD

**Issue by Zheaoli** [sindresorhus/alfred-npms#27] opened 2019-11-06 02:48 UTC
when I install alfred-npms , the npm raise an error 

> Error: Permission denied to read Alfred preferences at location /Users/manjusaka/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n

**Comment by sindresorhus** [comment] 2019-11-29 09:27
Duplicate of https://github.com/SamVerschueren/alfred-link/issues/22

**Closed by sindresorhus** 2019-11-29 09:27 UTC
